### ISSUE TITLE
Caches aren't valid JSON

### ISSUE THREAD

**Issue by hauleth** [fcpg/vim-complimentary#1]
Current caches generated by GAWK aren't proper JSON files, as standard forbids newlines in unescaped form in strings.

Also trailing commas aren't permitted by JSON specification.

**Comment by fcpg** [comment]
Tweaked the scripts a bit, let me know if there are remaining issues.

**Comment by hauleth** [comment]
@fcpg trailing commas are still present, and these aren't valid according to JSON spec:

![JSON spec business card](http://james.newtonking.com/images/JSONStandardBusinessCard_C4C7/image_3.png)

**Comment by fcpg** [comment]
Right, I only fixed the top-level ones.
Ok now?

**Comment by hauleth** [comment]
You can test it using [`jq`](https://stedolan.github.io/jq/). There are some unescaped slashes (ex. in `escape` function definition).

**Comment by fcpg** [comment]
jq seems happy now.

**Comment by hauleth** [comment]
Still one thing to go. It seems that `jq` accepts tabs in strings, this isn't allowed by default. I need to open issue in `jq` also.

EDIT: stedolan/jq#1544

**Comment by fcpg** [comment]
Good to go?

**Comment by hauleth** [comment]
Perfect.

**Comment by hauleth** [comment]
It seem that some unescaped tabs are left in `def_funccache.json`.

**Comment by fcpg** [comment]
Fixed.

The doc previously regrouped multiple return types right after the function name+args, eg. `submatch(...) String or List`, but for some new functions (ie. 'remote_startserver') they now put each return type on its own line, followed by the corresponding description.

The fix crudely checks for tabs in continuation lines, and if there's some, it assumes this is an alternate return type description.
