### ISSUE TITLE
Consider removing the 'menu' entry in Vim versions that support completeopt+=popup

### ISSUE THREAD

**Issue by bfrg** [fcpg/vim-complimentary#3]
Since Vim version [8.1.1880](https://github.com/vim/vim/commit/576a4a6ff14da876d7c4418e5f27e926fcfa8d2a) the 'info' field of `complete-items` can be displayed in a separate popup window., see `:h completeopt` for more details. Hence, we don't need the 'menu' field anymore since it doesn't show any additional information. Please consider removing it in newer Vim version.
![screenshot-2019-09-12_181957](https://user-images.githubusercontent.com/6266600/64802146-4e74ee80-d58a-11e9-8d2c-49ad66d51d94.png)

**Comment by fcpg** [comment]
Thanks for the suggestion. Just pushed a new commit, let me know if it works for you!

**Comment by bfrg** [comment]
Thanks for the fix. There is one issue though. When I complete after `call t<c-x><c-o>`, I get the error
```
Error detected while processing function complimentary#CompleteCpty:
line   69:
E715: Dictionary required
```
But completion after `call term_<c-x><c-o>` works fine.

**Comment by fcpg** [comment]
Took a quick look but could not reproduce. Added a type check anyway, hopefully it should take care of this error.

**Comment by bfrg** [comment]
Thank you. I think it works now and can be closed.
